---
apiVersion: v1
kind: Service
metadata:
  name: backend-v1-service
  annotations:
    service.beta.kubernetes.ios/aws-load-balancer-type: nlb
    service.beta.kubernetes.ios/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.ios/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: backend-v1-deployment

