---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: internal-nginx-svc
  annotations:
    service.beta.kubernetes.ios/aws-load-balancer-type: nlb
    service.beta.kubernetes.ios/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.ios/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: nginx 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80

